### ISSUE TITLE
[SUGGESTION] System PCH & CPU Type Variables

### ISSUE THREAD

**Issue by boomam** [MightySlaytanic/pve-monitoring#10]
Add  environment variables for cpu arch, pch name, etc. into the sh files.
Existing code references cannon-lake/similar, not every intel system is cannon-lake, and not every system is Intel.

Would allow the code to be more resilient to different system configs in the same way you have done with disk names.

[Example](https://github.com/MightySlaytanic/pve-monitoring/blob/e11c20e9dff1955ce7cb1fba2aa40b5c44b23c8f/pve_temp_stats_to_influxdb2.py#L61) - 
```
    stats["pch"] = int(data["pch_cannonlake-virtual-0"]["temp1"]["temp1_input"])
    stats["acpitz"] = int(data["acpitz-acpi-0"]["temp2"]["temp2_input"])
    stats["nvme-pci"] = int(data["nvme-pci-3a00"]["Composite"]["temp1_input"])
```
On a skylake system -  
* pch would need renaming too `pch_skylake-virtual-0`
* nvme would need renaming too `nvme-pci-0100`
* acpitz would need commenting out.

**Comment by MightySlaytanic** [comment]
Hi, have a look at the updated README where there is an example of /home/scripts/pve_temp_stats_to_influxdb2.sh, I've added 4 environment variables that can be setup like the following (in the example I suppose you have 2 nvme entries):

```
export PCH_INFO="pch:pch_cannonlake-virtual-0:temp1:temp1_input"
export ACPITZ_INFO="acpitz:acpitz-acpi-0:temp2:temp2_input"
export NVME_INFO="nvme:nvme-pci-3a00:Composite:temp1_input,nvme2:nvme-pci-XXXX:Composite:temp1_input"
export CORETEMP_NAME="coretemp-isa-0000"
```

If you do not have ACPITZ info, simply set it to ACPITZ_INFO=""

**Comment by boomam** [comment]
> Hi @boomam, have a look at the updated README where there is an example of /home/scripts/pve_temp_stats_to_influxdb2.sh, I've added 4 environment variables that can be setup like the following (in the example I suppose you have 2 nvme entries):
> 
> ```
> export PCH_INFO="pch:pch_cannonlake-virtual-0:temp1:temp1_input"
> export ACPITZ_INFO="acpitz:acpitz-acpi-0:temp2:temp2_input"
> export NVME_INFO="nvme:nvme-pci-3a00:Composite:temp1_input,nvme2:nvme-pci-XXXX:Composite:temp1_input"
> export CORETEMP_NAME="coretemp-isa-0000"
> ```
> 
> If you do not have ACPITZ info, simply set it to ACPITZ_INFO=""

That was quick!
I'll test it later this weekend, but it should be a great improvement regardless. :-)

**Comment by boomam** [comment]
Just tested, appears to work fine.

I'll submit a PR shortly to update the readme. :-)

**Comment by boomam** [comment]
https://github.com/MightySlaytanic/pve-monitoring/pull/11

Closing issue. :-)

**Comment by MightySlaytanic** [comment]
@boomam I've merged the readme and added acpitz info from my Intel NUC. Thanks.
