### ISSUE TITLE
[ERROR] KeyError: 'Core 4'

### ISSUE THREAD

**Issue by boomam** [MightySlaytanic/pve-monitoring#4]
When running the system temperature script, the following error is generated -  
```bash
Traceback (most recent call last):
  File "/home/scripts/pve_temp_stats_to_influxdb2.py", line 44, in <module>
    stats[f"core{index}"] = int(data["coretemp-isa-0000"][f"Core {index}"][f"temp{index+CORE_OFFSET}_input"])
KeyError: 'Core 4'
```

Output from lmsensors for comparison -  
```
pch_skylake-virtual-0
Adapter: Virtual device
temp1:        +50.5°C

nvme-pci-0100
Adapter: PCI adapter
Composite:    +44.9°C  (low  = -20.1°C, high = +77.8°C)
                       (crit = +81.8°C)
Sensor 1:     +44.9°C  (low  = -273.1°C, high = +65261.8°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +40.0°C  (high = +84.0°C, crit = +100.0°C)
Core 0:        +37.0°C  (high = +84.0°C, crit = +100.0°C)
Core 1:        +38.0°C  (high = +84.0°C, crit = +100.0°C)
Core 2:        +38.0°C  (high = +84.0°C, crit = +100.0°C)
Core 3:        +36.0°C  (high = +84.0°C, crit = +100.0°C)
```

**Comment by MightySlaytanic** [comment]
Hi, the purpose of the two python scripts is to give people an idea about how to monitor their PVE instances and upload data to influxdb2, the code is not parameterized and issues may arise if you have different sensors or hardware configurations. For example I have 6 cores and you have 4 cores, so you must change the range from 0..6 to 0..4.
Everything could be parameterized but unfortunately I had no time and I really don't know how many different outputs we could have from sensors on different systems.

```python
 for index in range(0,6):
        stats[f"core{index}"] = int(data["coretemp-isa-0000"][f"Core {index}"][f"temp{index+CORE_OFFSET}_input"])
```

**Comment by boomam** [comment]
Hi, 
Let me test with that new code, if so, an adjustment to the readme could be in order to save parameterization. :-)
One moment whilst i test...

**Comment by boomam** [comment]
ok, that seemed to have done it, along with another adjustment. 
I'll update that PR i made to reflect this.

**Comment by MightySlaytanic** [comment]
I have already merged your changes and added a CPU_CORES variable to the pve_temp example bash file and implemented within the corresponding python script

**Comment by MightySlaytanic** [comment]
I have added you in the AUTHORS file, feel free to add other links/info about yourself

**Comment by boomam** [comment]
> I have added you in the AUTHORS file, feel free to add other links/info about yourself

Thanks! Its your script though, great work on it!
My issue now is getting Influxdb2 to behave, i dont know what they did between 1.8 & 2, but 2 is...questionable. :-p

I think this can be closed now.

**Comment by MightySlaytanic** [comment]
I think that from 1.x to 2.x a lot of stuff changed in InfluxDB and WriteAPI should be different

**Comment by boomam** [comment]
Its more so it actually starting correctly and not bombing out. Never had much luck with it on Unraid, works perfectly fine on 'normal' docker though.
