### ISSUE TITLE
[ERROR] Disk Stats/Temps - 'NoneType'

### ISSUE THREAD

**Issue by boomam** [MightySlaytanic/pve-monitoring#9]
Using new script - 

```
Traceback (most recent call last):
  File "/home/scripts/./pve_disks_stats_to_influxdb2.py", line 35, in <module>
    DATA_UNITS_READ_BASE = int(getenv("DATA_UNITS_READ_BASE"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

Commenting out DATA_UNITS_READ instead generates this error
```
Traceback (most recent call last):
  File "/home/scripts/./pve_disks_stats_to_influxdb2.py", line 37, in <module>
    SATA_DISKS = getenv("SATA_DISKS").split(',')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by boomam** [comment]
Self - Resolved error above, forgot to adjust the python env path in the sh file, however, new error when running - 
```

```

**Comment by boomam** [comment]
Little more testing, i can confirm that the drive stats are not coming through.  
I'll do some more thorough testing in the morning.

**Comment by MightySlaytanic** [comment]
Hi @boomam, you could add `print(f"*** DATA ***\n {data} \n*** NVME_INFO ***\n {NVME_INFO} \n") ` at line 64 to see the output of sensors and understand why it does not print NVME data. Do you get the other info and only NVME info is missing?

**Comment by boomam** [comment]
Morning @MightySlaytanic, can you clarify - 

- Line 64 including the commented out info?
  - Including the data, the existing line reads `if len(line) > 0:`
  - Not including the data, the existing line reads `match_temp_value = re.match(r"(\d+).*", value)`
- Replacing what is already there, or adding to the end?

**Comment by MightySlaytanic** [comment]
@boomam sorry, my mistake, I was thinking about the other script.. you can print the output variable after the nvmcli command is executed or execute the command nvmcli with the syntax in the script and see which info do you collect.

**Comment by boomam** [comment]
Can you clarify what you mean about "output variable after the nvmcli" ? 
The disk script doesn't use nvmcli from what I can see? Theres no references to it?

**Comment by boomam** [comment]
I think its solved now - I noticed that one of my nodes was behaving, the one I was testing was not.
Rebooted the one that was not and....bizarrely it starts working after a reboot.

Let me do a 'new' implementation on my PBS, see what that does from a fresh set of code copy/pasted form the repo. 
Will report back.

**Comment by boomam** [comment]
Seems to be collecting data still, so we can consider this as solved.
